### PR TITLE
Add `git-duet-merge`

### PR DESCRIPTION
**Pull request by wendorf**
Because merging does not support the --signoff flag, we have to do it
manually.
1. Do the merge as normal: `git merge [branch_name]`
2. Amend the merge commit by adding the signoff:
   - `git commit --amend --no-edit --signoff`

Note that this does appear a little different to the user if adding the
commit message interactively (e.g. not using `git duet-commit -m"message"`).
The "Signed-off-by" line will not appear when writing the
commit message, but is only added after entering the message.

### CODE REVIEW

**Comment by jszwedko** [comment]
@wendorf :clap: :trumpet: thanks for putting this together!

I ran into the same road block of the lack of `--signoff` on `git merge` when I considered doing `git duet-merge`, but hadn't thought of this approach. I also like the abstraction you created around running the `git (merge|revert|commit)` and the tests.

My only qualm is around how we transparently proxy flags/arguments to the the analogous git commands and how this will play with passing the same argument set to `git merge` and `git commit`. As a user, I'd expect the arguments/flags to be passed to `git merge`, but I'm not sure if we'll see any unexpected behavior by passing the same flags to `git commit`. What do you think about avoiding reading from `os.Args` during the `git commit --amend` by modifying the abstraction?

**Comment by wendorf** [comment]
@jszwedko That should be the behavior in this PR. The New(subcommand string, args ...string) method looks at the length of the passed in args. If it's zero, it proxies the user's args. If it's non-zero, though, the explicit args are used instead.

Because that wasn't clear, it might mean that a refactor or rename is in order to improve the code's readability. Just let me know if you need me to make adjustments.

**Comment by jszwedko** [comment]
And so it is! Do you mind adding a comment to that function to make that clearer. Otherwise, I think this is good to go.

**Comment by wendorf** [comment]
Sounds good. Just added the comment.

**Comment by jszwedko** [comment]
:clap:

**Pull request merged**
