### PR TITLE
Allow multiple committers if GIT_DUET_ALLOW_MULTIPLE_COMMITTERS is set

### PR DESCRIPTION
**Pull request by liying-kwa**
If GIT_DUET_ALLOW_MULTIPLE_COMMITTERS=1 is set, git duet will:
* [git duet-commit, git duet-merge] Add sign-off trailers for every committer specified after the author
* [git duet] Print the author and all committers specified

### CODE REVIEW

**Comment by liying-kwa** [comment]
Hi there @rafecolton @jszwedko, I saw that you two have been reviewing recent PRs. Could you advise me on how I can get this PR reviewed and merged? Thank you!

**Review by jszwedko — DISMISSED** [review]
This looks good, thanks for the contribution @liying-kwa !

**Comment by jszwedko** [comment]
@liying-kwa do you mind squashing and signing the commit? We currently require signed commits in order to be merged.

**Comment by liying-kwa** [comment]
Hi @jszwedko, I've squashed and signed the commit. Thank you so much for reviewing it!!

**Review by jszwedko — APPROVED** [review]
Great, thanks @liying-kwa !

**Comment by liying-kwa** [comment]
@jszwedko I don't have write access to the repo... Could you help me merge this PR? Thank you!

**Pull request merged**
