### PR TITLE
Switch CI to Github Actions

### PR DESCRIPTION
**Pull request by jszwedko**
This is turning into a bit of a rabbit hole :sweat_smile: The latest release build failed due to the credentials being invalid. Rather than go through and remember how to generate them for Travis CI, I figured I'd take the time to just switch us over to Github Actions, which has tighter integration with Github.

Additionally:

* TravisCI is no longer indefinitely free for open source projects.
* I think using Github Actions is also more likely to be familiar to possible contributors.

Signed-off-by: Jesse Szwedko <jesse.szwedko@gmail.com>

### CODE REVIEW

**Comment by rafecolton** [comment]
Yeah makes sense at this point. Bummer about Travis's free plans. LMK when tests pass and I'll give this a full review

**Comment by jszwedko** [comment]
@rafecolton should be good now if you want to take a look when you have time.

**Review by rafecolton — APPROVED** [review]

**Comment by jszwedko** [comment]
:+1: I was hoping to do a "Squash and Merge" for that one given all of the incremental commits, but no big deal.

**Comment by rafecolton** [comment]
Ah yeah I usually just merge and keep the history 🤷‍♀️ oh well next time

**Pull request merged**
