### PR TITLE
Update README to say JetBrains IDE instead of RubyMine. rename script…

### PR DESCRIPTION
**Pull request by iumehara**
This rename clarifies that the git wrapper works with JetBrains IDEs besides RubyMine.

I think it's potentially confusing to use an executable called rubymine-git-wrapper for IDEs beside RubyMine.

### CODE REVIEW

**Comment by rafecolton** [comment]
Change makes sense. Can you please fix the broken tests?

**Comment by iumehara** [comment]
Reopening to re-run travis tests.
Tests 61 and 106, which failed in the initial pull request, pass locally. (although different tests fail locally)

**Comment by rafecolton** [comment]
Are you running the tests in the docker container? That should produce results most consistent with what you see in Travis

**Comment by iumehara** [comment]
I didn't use docker. 
Can you tell me what image Travis is using?
I will give it a try with Docker. (Although, not super confident in debugging this as I haven't worked with golang before.)

**Comment by rafecolton** [comment]
See https://github.com/git-duet/git-duet/blob/master/scripts/test-docker

**Comment by rafecolton** [comment]
I'm guessing there's just a test that expects the file being to be named `rubymine-git-wrapper`, but if there's an unrelated failure, paste the output here and we'll work on it

**Comment by iumehara** [comment]
hm.., so the docker tests  are passing. (./scripts/test-docker from my rename-rubymine-to-jetbrains branch)
I printed out `git branch` to make sure I'm testing the correct branch, and it looks like I am.
I also don't see any use of the words "rubymine" or "git-wrapper" in the codebase outside of the README and changelog.

The failed tests on CI are:
```
not ok 61 as duet: does not write Co-authored-by trailer when rebasing if GIT_DUET_CO_AUTHORED_BY
# (in test file test/git-as.bats, line 500)
#   `[[ ! $output = *"Co-authored-by:"* ]]' failed
# [master (root-commit) 22e8515] test commit for reverting
#  1 file changed, 0 insertions(+), 0 deletions(-)
#  create mode 100644 foo
# git-duet-install-hook: Installed hook to /tmp/git-duet/repo/.git/hooks/prepare-commit-msg
# Current branch master is up to date, rebase forced.
Successfully rebased and updated refs/heads/master.
# fatal: no such section: foo.bar
```

and:
```
not ok 106 does not write Co-authored-by trailer when rebasing if GIT_DUET_CO_AUTHORED_BY
# (in test file test/git-duet.bats, line 298)
#   `[[ ! $output = *"Co-authored-by:"* ]]' failed
# [master (root-commit) afbbc74] test commit for reverting
#  1 file changed, 0 insertions(+), 0 deletions(-)
#  create mode 100644 foo
# git-duet-install-hook: Installed hook to /tmp/git-duet/repo/.git/hooks/prepare-commit-msg
# Current branch master is up to date, rebase forced.
Successfully rebased and updated refs/heads/master.
# fatal: no such section: foo.bar
```

Any thoughts on how best to proceed?

**Comment by rafecolton** [comment]
Hm, I'm actually not sure. I'm seeing the same thing - tests pass on localhost with and without your change. @jszwedko any thoughts on what might be causing this?

**Comment by jszwedko** [comment]
Hmm, I actually get these failures locally (both on master and in this branch) but only when running outside of docker. I'm wondering if it is a difference in `git` or `bats` versions. I'm taking a look.

**Comment by jszwedko** [comment]
I haven't been able to verify yet as I'm getting different failures using a `git` that I compiled, but my suspicion is that it is related to the git version.

Locally I saw the failure with 2.28.0
TravisCI is using 2.27.0
`scripts/test-docker` uses 2.20.1

I personally think it'd be fine to merge this PR though, given the failures are also on master, and open a follow-up issue to debug the test failure.

**Review by rafecolton — DISMISSED** [review]
Works for me!

**Comment by rafecolton** [comment]
@iumehara will you please sign your commit? After that, we can merge it and create a separate issue to fix the broken tests.

**Comment by iumehara** [comment]
@rafecolton 
Just pushed a signed commit. Thanks!

**Review by rafecolton — APPROVED** [review]

**Comment by rafecolton** [comment]
Thanks! Merged and created https://github.com/git-duet/git-duet/issues/92 as a followup

**Pull request merged**
